### PR TITLE
Add yAxisType command to repl

### PR DESCRIPTION
**Pull request by berrytj**
Here's one possible approach – let me know what you think.

### CODE REVIEW

**Comment by berrytj** [comment]
I can add this for the x axis too, but it's making the plot disappear right now so I'll have to dig into it

**Comment by AustinBGibbons** [comment]
Hey, this is great, thanks! A few thoughts:

- Can you change the axisType type signature to use `AxisType.Type` instead of String? I think it should work as a drop-in replacement
- It might be useful to expose the acceptable parameters (linear, logarithmic, datetime, category) through the help command
- Are you happy with the values provided by highcharts? We could consider alternate naming strategies (log10, logE, log2, for example) and perform the necessary conversion ourselves. 
- We can check that it's one of the correct input options, I think if it's mistyped now it silently ignores the axis type.
- you're setting the axis name/type by mapping over the y-axis option. The default values for this are:

```
xAxis: Option[Array[Axis]] = None,
yAxis: Option[Array[Axis]] = Some(Array(Axis()))
```

(this is because we use other default settings than highcharts.js does, but do not do so for the x-axis). I suspect this is why the x-axis is disappearing. Ideally, we would copy the `Some(Array(Axis))` as you do here, and if it is currently `None`, set either its name/type

For the method names - I'm not complete sure what I would like them to be called - what do you think?
- leave as is - yAxis(String) refers to axis name, yAxisType(AxisType.Type) referes to axis type
- offer yAxisName(String), yAxisTitle(AxisType.Type) as separate methods
- yAxis(name: String, type: AxisType.Type) - perhaps supplying default values to make yAxis(name) possible?
- yAxis(name: String)

or some combination of these ideas.

I threw a lot of stuff up here - I should be able to help code it out tomorrow evening if you'd like my assistance!

**Comment by berrytj** [comment]
(working on this)

**Comment by berrytj** [comment]
– axisType type signature changed
– Valid parameters exposed via help
– I'd lean towards just adding `log` (log10) for now, matching the highcharts (and matplotlib) default.  We can add the others (and a `log10` alias) as needed.
– I added a message that prints if an invalid axisType is entered
– Haven't gotten a chance to look at the xAxis stuff yet
– Not sure about the method names.  I'd lean toward this implementation because of its straightforwardness, but would be happy with the others you've suggested

**Comment by berrytj** [comment]
Ah, the problem was that one of my x values was 0 – which you can't take the log of.  Works now.

**Comment by AustinBGibbons** [comment]
Looks good to me! Thanks for submitting this PR Tom :)

**Pull request merged**
