### PR TITLE
Fix for #22

### PR DESCRIPTION
**Pull request by slothspot**
Hi @mandubian, I propose following fix for #22. It implies dependency on JDK7 due to Files class usage,
but I see no big problem here

### CODE REVIEW

**Comment by AustinBGibbons** [comment]
Thanks for submitting this PR! It looks like the changed line fails if the file already exists, perhaps the test cases ran within the same millisecond?




We should probably delete the files made in the test cases, and perhaps separately guard against the file already existing




Can someone at Quantifind check this out, especially w.r.t. To Java 1.6? I am traveling and may be slow to respond.



—

**Comment by haeley-qf** [comment]
@slothspot What's the feature branch? I'd like to look at it.

**Comment by slothspot** [comment]
@haeley-qf I have not created one, so you may check commits  slothspot/wisp@2c7e389 and slothspot/wisp@f842cd2 individually

**Comment by slothspot** [comment]
@AustinBGibbons I'll take a look into test cases and check guards logic

**Comment by slothspot** [comment]
@haeley-qf , @AustinBGibbons  Should I modify .travis.yml to add dependency to JDK7 as well or modify code to target JDK 1.6 ?

**Comment by slothspot** [comment]
@AustinBGibbons , @haeley-qf Close this one in favour of #24

**Pull request closed without merging**
